name: module_atendimento
description: MÃ³dulo de atendimento com kanban e chat integrado
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  cloud_firestore: ^6.1.0
  lucide_icons: ^0.257.0
  flutter_colorpicker: ^1.0.3
  intl: ^0.19.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.2
  module_leads:
    path: ../module_leads
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  http: ^1.6.0
  just_audio_windows: ^0.2.2
  file_picker: ^10.3.7
  record: ^6.1.2
  permission_handler: ^12.0.1
  path_provider_windows: ^2.3.0
  cloud_functions: ^6.0.5
  video_player: ^2.10.1
  chewie: ^1.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
