name: module_atendimento
description: MÃ³dulo de atendimento com kanban e chat integrado
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  cloud_firestore: ^6.1.0
  lucide_icons: ^0.257.0
  flutter_colorpicker: ^1.0.3
  intl: ^0.19.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.2
  module_leads:
    path: ../module_leads

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
