name: module_leads
description: MÃ³dulo de gerenciamento de leads do sistema SIGE.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  lucide_icons: ^0.257.0
  intl: ^0.19.0
  data_table_2: ^2.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
