name: module_map
description: Modulo de mapas personalizavel.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_riverpod: ^2.4.9
  http: ^1.1.0
  lucide_icons: ^0.257.0
  core:
    path: ../core
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
